// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "ui.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(401, 222);
    w = o; if (w) {/* empty */}
    { new Fl_Button(155, 75, 64, 20, "Click me!");
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
